### ISSUE TITLE
Error: Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by hautest** [lifeisegg123/reastorage#28]
Hi. I'm currently using @reastorage/react in the following js and I'm getting this error when upgrading to version 1.3.0. After analyzing the cause, it seems to be an issue with the package.json export field in [this commit](https://github.com/lifeisegg123/reastorage/commit/19fde11d5d3630e46e532cad47542a8d41b072f7). I forked it after seeing [this stackoverflow](https://stackoverflow.com/questions/76127288/module-not-found-error-default-condition-should-be-last-one) and tried to modify it, but it works fine when the default attribute is down, is it okay if I modify it ?

<img width="970" alt="스크린샷 2024-06-18 오후 4 37 05" src="https://github.com/lifeisegg123/reastorage/assets/100465780/4acd19e7-456c-48d5-8c05-870e0432b6bb">

**Comment by hautest** [comment]
I think it's probably an issue when using webpack.

https://webpack.js.org/guides/package-exports/

<img width="737" alt="스크린샷 2024-06-18 오후 4 51 21" src="https://github.com/lifeisegg123/reastorage/assets/100465780/928d5192-a605-471c-928c-032b4032e9bc">

**Comment by hautest** [comment]
When I find a module in the webpack, it finds it in the order of that object, but the default attribute is always the matching attribute and it is on top, so I need to find types, but the default attribute is applied, so I can't read types. 

<img width="757" alt="스크린샷 2024-06-18 오후 5 35 00" src="https://github.com/lifeisegg123/reastorage/assets/100465780/849f0e2d-844c-4f1f-9d47-d41b40bd775c">

**Comment by lifeisegg123** [comment]
resolved in #29
